version: '3.4'
networks:
  shared:
    external: 
      name : shared

services:
  postgresdb:
    networks:
      - shared
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgresdb:/var/lib/postgresql/data

  redis:
    networks:
      - shared
    image: redis
    command: redis-server 
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - 'redis:/data'

  web:
    networks:
      - shared
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgresdb
      - redis
  
volumes:
  redis: {}
  postgresdb: 
    driver: local




  

